### ISSUE TITLE
Automatic error report for Desktop App gauzy-desktop 0.285.5

### ISSUE THREAD

**Issue by eball218** [ever-co/ever-gauzy-desktop#10]
Error:
```UnhandledRejection TypeError: Cannot read properties of null (reading 'loadURL')
    at C:\Program Files\Ever\Gauzy Desktop\resources\app.asar\index.js:375:27
    at Generator.next (<anonymous>)
    at C:\Program Files\Ever\Gauzy Desktop\resources\app.asar\index.js:28:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Program Files\Ever\Gauzy Desktop\resources\app.asar\index.js:24:12)
    at IpcMainImpl.<anonymous> (C:\Program Files\Ever\Gauzy Desktop\resources\app.asar\index.js:365:48)
    at IpcMainImpl.emit (node:events:527:28)
    at IpcMainImpl.emit (node:domain:475:12)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
    at EventEmitter.emit (node:events:527:28)
```
OS: Windows NT 10.0.22621

**Comment by evereq** [comment]
@eball218 are you using pre-release or release?

**Comment by eball218** [comment]
Release
